### PR TITLE
Update query.py

### PR DESCRIPTION
**Pull request by LeoKudrik**
SQLCompiler.get_columns returning list (result, params)
https://github.com/django/django/commit/e74e207cce54802f897adcb42149440ee154821e

### CODE REVIEW

**Comment by kanu** [comment]
Why should only the first column be returned?
Or do i miss something?

**Comment by LeoKudrik** [comment]
Method SQLCompiler.get_columns now returning list ([column1, column2, column3], params). See commit https://github.com/django/django/commit/e74e207cce54802f897adcb42149440ee154821e and file django/db/models/sql/compiler.py. 10 months ago :)

**Comment by kanu** [comment]
Thank you @LeoKudrik. I am still on 1.5 so I havn't notice the changes.

**Comment by LeoKudrik** [comment]
thanks for your update_returning

**Pull request merged**
